files:
  - source: '**/**.md'
    ignore:
      - '**/initial_state.md'
      - '**/final_state.md'
    translation: /%locale%/%original_path%/%original_file_name%
  - source: '**/meta.yml'
    translation: /%locale%/%original_path%/%original_file_name%
