---
locale: es
tags: [ ]
layout: input_kids
editor: custom
type: problem
extra_visible: false
teacher_info: 'En esta actividad encontramos un nuevo procedimiento: `Volar al`. Podemos pensar y explorar con nuestros estudiantes qué es lo que hace utilizando el ojito sobre el tablero :eye:. Es importante distinguir `Volar al` de `Mover`, y el rol de la abeja a lo largo de la lección.'
manual_evaluation: false
choices: [ ]
name: Vuela vuela
